services:
  db:
    image: postgres:16
    container_name: road-flood-postgres
    restart: always
    environment:
      POSTGRES_DB: flood_ai
      POSTGRES_USER: flood_user
      POSTGRES_PASSWORD: flood_pass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
